/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MediaRouteImport } from './routes/media'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs_.$slug'
import { Route as NewsSlugRouteImport } from './routes/news_.$slug'
import { Route as DocumentationIdRouteImport } from './routes/documentation_.$id'
import { Route as ApiVolunteerRouteImport } from './routes/api/volunteer'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthenticatedRouteRouteImport } from './routes/admin/_authenticated/route'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedVolunteersRouteImport } from './routes/admin/_authenticated/volunteers'
import { Route as AdminAuthenticatedProgramsRouteImport } from './routes/admin/_authenticated/programs'
import { Route as AdminAuthenticatedPartnersRouteImport } from './routes/admin/_authenticated/partners'
import { Route as AdminAuthenticatedNewsRouteImport } from './routes/admin/_authenticated/news'
import { Route as AdminAuthenticatedMessagesRouteImport } from './routes/admin/_authenticated/messages'
import { Route as AdminAuthenticatedMediaRouteImport } from './routes/admin/_authenticated/media'
import { Route as AdminAuthenticatedEventsRouteImport } from './routes/admin/_authenticated/events'
import { Route as AdminAuthenticatedDocumentsRouteImport } from './routes/admin/_authenticated/documents'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs_/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIdRoute = DocumentationIdRouteImport.update({
  id: '/documentation_/$id',
  path: '/documentation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVolunteerRoute = ApiVolunteerRouteImport.update({
  id: '/api/volunteer',
  path: '/api/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRouteRoute = AdminAuthenticatedRouteRouteImport.update({
  id: '/admin/_authenticated',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRouteRoute,
} as any)
const AdminAuthenticatedVolunteersRoute =
  AdminAuthenticatedVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedProgramsRoute =
  AdminAuthenticatedProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedPartnersRoute =
  AdminAuthenticatedPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedNewsRoute = AdminAuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminAuthenticatedRouteRoute,
} as any)
const AdminAuthenticatedMessagesRoute =
  AdminAuthenticatedMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedMediaRoute = AdminAuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAuthenticatedRouteRoute,
} as any)
const AdminAuthenticatedEventsRoute =
  AdminAuthenticatedEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)
const AdminAuthenticatedDocumentsRoute =
  AdminAuthenticatedDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AdminAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AdminAuthenticatedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/api/volunteer': typeof ApiVolunteerRoute
  '/documentation/$id': typeof DocumentationIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/documents': typeof AdminAuthenticatedDocumentsRoute
  '/admin/events': typeof AdminAuthenticatedEventsRoute
  '/admin/media': typeof AdminAuthenticatedMediaRoute
  '/admin/messages': typeof AdminAuthenticatedMessagesRoute
  '/admin/news': typeof AdminAuthenticatedNewsRoute
  '/admin/partners': typeof AdminAuthenticatedPartnersRoute
  '/admin/programs': typeof AdminAuthenticatedProgramsRoute
  '/admin/volunteers': typeof AdminAuthenticatedVolunteersRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/api/volunteer': typeof ApiVolunteerRoute
  '/documentation/$id': typeof DocumentationIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/admin/documents': typeof AdminAuthenticatedDocumentsRoute
  '/admin/events': typeof AdminAuthenticatedEventsRoute
  '/admin/media': typeof AdminAuthenticatedMediaRoute
  '/admin/messages': typeof AdminAuthenticatedMessagesRoute
  '/admin/news': typeof AdminAuthenticatedNewsRoute
  '/admin/partners': typeof AdminAuthenticatedPartnersRoute
  '/admin/programs': typeof AdminAuthenticatedProgramsRoute
  '/admin/volunteers': typeof AdminAuthenticatedVolunteersRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/contact': typeof ApiContactRoute
  '/api/volunteer': typeof ApiVolunteerRoute
  '/documentation_/$id': typeof DocumentationIdRoute
  '/news_/$slug': typeof NewsSlugRoute
  '/programs_/$slug': typeof ProgramsSlugRoute
  '/admin/_authenticated/documents': typeof AdminAuthenticatedDocumentsRoute
  '/admin/_authenticated/events': typeof AdminAuthenticatedEventsRoute
  '/admin/_authenticated/media': typeof AdminAuthenticatedMediaRoute
  '/admin/_authenticated/messages': typeof AdminAuthenticatedMessagesRoute
  '/admin/_authenticated/news': typeof AdminAuthenticatedNewsRoute
  '/admin/_authenticated/partners': typeof AdminAuthenticatedPartnersRoute
  '/admin/_authenticated/programs': typeof AdminAuthenticatedProgramsRoute
  '/admin/_authenticated/volunteers': typeof AdminAuthenticatedVolunteersRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/documentation'
    | '/donate'
    | '/events'
    | '/media'
    | '/news'
    | '/partnerships'
    | '/programs'
    | '/volunteer'
    | '/admin'
    | '/admin/login'
    | '/api/contact'
    | '/api/volunteer'
    | '/documentation/$id'
    | '/news/$slug'
    | '/programs/$slug'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/programs'
    | '/admin/volunteers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/documentation'
    | '/donate'
    | '/events'
    | '/media'
    | '/news'
    | '/partnerships'
    | '/programs'
    | '/volunteer'
    | '/admin/login'
    | '/api/contact'
    | '/api/volunteer'
    | '/documentation/$id'
    | '/news/$slug'
    | '/programs/$slug'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/news'
    | '/admin/partners'
    | '/admin/programs'
    | '/admin/volunteers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/documentation'
    | '/donate'
    | '/events'
    | '/media'
    | '/news'
    | '/partnerships'
    | '/programs'
    | '/volunteer'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/api/contact'
    | '/api/volunteer'
    | '/documentation_/$id'
    | '/news_/$slug'
    | '/programs_/$slug'
    | '/admin/_authenticated/documents'
    | '/admin/_authenticated/events'
    | '/admin/_authenticated/media'
    | '/admin/_authenticated/messages'
    | '/admin/_authenticated/news'
    | '/admin/_authenticated/partners'
    | '/admin/_authenticated/programs'
    | '/admin/_authenticated/volunteers'
    | '/admin/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DocumentationRoute: typeof DocumentationRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  ProgramsRoute: typeof ProgramsRoute
  VolunteerRoute: typeof VolunteerRoute
  AdminAuthenticatedRouteRoute: typeof AdminAuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiVolunteerRoute: typeof ApiVolunteerRoute
  DocumentationIdRoute: typeof DocumentationIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/$slug': {
      id: '/programs_/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$slug': {
      id: '/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation_/$id': {
      id: '/documentation_/$id'
      path: '/documentation/$id'
      fullPath: '/documentation/$id'
      preLoaderRoute: typeof DocumentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/volunteer': {
      id: '/api/volunteer'
      path: '/api/volunteer'
      fullPath: '/api/volunteer'
      preLoaderRoute: typeof ApiVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/volunteers': {
      id: '/admin/_authenticated/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminAuthenticatedVolunteersRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/programs': {
      id: '/admin/_authenticated/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminAuthenticatedProgramsRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/partners': {
      id: '/admin/_authenticated/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminAuthenticatedPartnersRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/news': {
      id: '/admin/_authenticated/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminAuthenticatedNewsRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/messages': {
      id: '/admin/_authenticated/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAuthenticatedMessagesRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/media': {
      id: '/admin/_authenticated/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAuthenticatedMediaRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/events': {
      id: '/admin/_authenticated/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminAuthenticatedEventsRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
    '/admin/_authenticated/documents': {
      id: '/admin/_authenticated/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminAuthenticatedDocumentsRouteImport
      parentRoute: typeof AdminAuthenticatedRouteRoute
    }
  }
}

interface AdminAuthenticatedRouteRouteChildren {
  AdminAuthenticatedDocumentsRoute: typeof AdminAuthenticatedDocumentsRoute
  AdminAuthenticatedEventsRoute: typeof AdminAuthenticatedEventsRoute
  AdminAuthenticatedMediaRoute: typeof AdminAuthenticatedMediaRoute
  AdminAuthenticatedMessagesRoute: typeof AdminAuthenticatedMessagesRoute
  AdminAuthenticatedNewsRoute: typeof AdminAuthenticatedNewsRoute
  AdminAuthenticatedPartnersRoute: typeof AdminAuthenticatedPartnersRoute
  AdminAuthenticatedProgramsRoute: typeof AdminAuthenticatedProgramsRoute
  AdminAuthenticatedVolunteersRoute: typeof AdminAuthenticatedVolunteersRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteRouteChildren: AdminAuthenticatedRouteRouteChildren =
  {
    AdminAuthenticatedDocumentsRoute: AdminAuthenticatedDocumentsRoute,
    AdminAuthenticatedEventsRoute: AdminAuthenticatedEventsRoute,
    AdminAuthenticatedMediaRoute: AdminAuthenticatedMediaRoute,
    AdminAuthenticatedMessagesRoute: AdminAuthenticatedMessagesRoute,
    AdminAuthenticatedNewsRoute: AdminAuthenticatedNewsRoute,
    AdminAuthenticatedPartnersRoute: AdminAuthenticatedPartnersRoute,
    AdminAuthenticatedProgramsRoute: AdminAuthenticatedProgramsRoute,
    AdminAuthenticatedVolunteersRoute: AdminAuthenticatedVolunteersRoute,
    AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
  }

const AdminAuthenticatedRouteRouteWithChildren =
  AdminAuthenticatedRouteRoute._addFileChildren(
    AdminAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DocumentationRoute: DocumentationRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRoute,
  PartnershipsRoute: PartnershipsRoute,
  ProgramsRoute: ProgramsRoute,
  VolunteerRoute: VolunteerRoute,
  AdminAuthenticatedRouteRoute: AdminAuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiContactRoute: ApiContactRoute,
  ApiVolunteerRoute: ApiVolunteerRoute,
  DocumentationIdRoute: DocumentationIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
