/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MediaRouteImport } from './routes/media'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsSlugRouteImport } from './routes/programs_.$slug'
import { Route as NewsSlugRouteImport } from './routes/news_.$slug'
import { Route as DocumentationIdRouteImport } from './routes/documentation_.$id'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs_/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationIdRoute = DocumentationIdRouteImport.update({
  id: '/documentation_/$id',
  path: '/documentation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/volunteer': typeof VolunteerRoute
  '/documentation/$id': typeof DocumentationIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/volunteer': typeof VolunteerRoute
  '/documentation/$id': typeof DocumentationIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/programs/$slug': typeof ProgramsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documentation': typeof DocumentationRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/programs': typeof ProgramsRoute
  '/volunteer': typeof VolunteerRoute
  '/documentation_/$id': typeof DocumentationIdRoute
  '/news_/$slug': typeof NewsSlugRoute
  '/programs_/$slug': typeof ProgramsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/documentation'
    | '/donate'
    | '/events'
    | '/media'
    | '/news'
    | '/partnerships'
    | '/programs'
    | '/volunteer'
    | '/documentation/$id'
    | '/news/$slug'
    | '/programs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/documentation'
    | '/donate'
    | '/events'
    | '/media'
    | '/news'
    | '/partnerships'
    | '/programs'
    | '/volunteer'
    | '/documentation/$id'
    | '/news/$slug'
    | '/programs/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/documentation'
    | '/donate'
    | '/events'
    | '/media'
    | '/news'
    | '/partnerships'
    | '/programs'
    | '/volunteer'
    | '/documentation_/$id'
    | '/news_/$slug'
    | '/programs_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DocumentationRoute: typeof DocumentationRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  ProgramsRoute: typeof ProgramsRoute
  VolunteerRoute: typeof VolunteerRoute
  DocumentationIdRoute: typeof DocumentationIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs_/$slug': {
      id: '/programs_/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$slug': {
      id: '/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation_/$id': {
      id: '/documentation_/$id'
      path: '/documentation/$id'
      fullPath: '/documentation/$id'
      preLoaderRoute: typeof DocumentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DocumentationRoute: DocumentationRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRoute,
  PartnershipsRoute: PartnershipsRoute,
  ProgramsRoute: ProgramsRoute,
  VolunteerRoute: VolunteerRoute,
  DocumentationIdRoute: DocumentationIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
